-- NORMALISATION
-- Q)1
CREATE TABLE DEPARTMENTS (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);


CREATE TABLE EMPLOYEES (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(50),
    SAL DECIMAL(10, 2),
    DEPTNO INT,
    FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENTS(DEPTNO)
);

-- Q.2
CREATE TABLE STUDENT_PROFILE (
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT
);


CREATE TABLE STUDENT_PERFORMANCE (
    ROLLNO INT,
    EXAM VARCHAR(50),
    MARKS INT,
    GRADE VARCHAR(2),
    PRIMARY KEY (ROLLNO, EXAM),
    FOREIGN KEY (ROLLNO) REFERENCES STUDENT_PROFILE(ROLLNO)
);

-- Q.3
CREATE TABLE PROJECT_CUSTOMERS (
    PROJECT_NO VARCHAR(20) PRIMARY KEY,
    CUSTOMERNAME VARCHAR(100)
);

CREATE TABLE PROJECT_ASSIGNMENTS (
    EMPNO INT,
    PROJECT_NO VARCHAR(20),
    NO_OF_DAYS INT,
    PRIMARY KEY (EMPNO, PROJECT_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT_CUSTOMERS(PROJECT_NO)
);

