-- DISPLAYING DATA FROM FROM MULTIPLE TABLES USING JOIN
-- Q.1
SELECT EMPNO, ENAME, SAL, DNAME, LOC
FROM EMP
NATURAL JOIN DEPT;

-- Q.2
SELECT E.JOB, E.MGR, E.SAL, E.COMM, D.DNAME
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = 'SALESMAN';

-- Q.3
SELECT E.ENAME, E.JOB, E.DEPTNO, D.DNAME
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE D.LOC = 'DALLAS';

-- Q.4
SELECT
E.ENAME AS Employee,
E.EMPNO AS "Emp#",
M.ENAME AS Manager,
M.EMPNO AS "Mgr#"
FROM EMP E
JOIN EMP M
ON E.MGR = M.EMPNO;

-- Q.5
SELECT
E.ENAME AS Employee,
E.EMPNO AS "Emp#",
M.ENAME AS Manager,
M.EMPNO AS "Mgr#"
FROM EMP E
LEFT OUTER JOIN EMP M
ON E.MGR = M.EMPNO
ORDER BY E.EMPNO;

-- Q.6
DESC SALGRADE;

SELECT
E.ENAME,
E.JOB,
D.DNAME,
E.SAL,
S.GRADE
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- Q.7
SELECT E.ENAME, D.DNAME
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

-- Q.8
SELECT
E.ENAME AS Employee,
E.HIREDATE AS Employee_Hiredate,
M.ENAME AS Manager,
M.HIREDATE AS Manager_Hiredate
FROM EMP E
LEFT OUTER JOIN EMP M
ON E.MGR = M.EMPNO
WHERE E.HIREDATE < M.HIREDATE;

-- Q.9
SELECT EMPNO, ENAME, DNAME, LOC
FROM EMP
JOIN DEPT
USING (DEPTNO)
WHERE JOB = 'CLERK';

-- Q.10
SELECT E.ENAME, E.SAL, E.MGR, D.DNAME
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.SAL > 2000;

-- Q.11
SELECT
E.EMPNO,
E.ENAME,
E.JOB,
E.DEPTNO,
D.DNAME,
D.LOC
FROM EMP E
LEFT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

-- Q.12
SELECT
E.ENAME,
D.DNAME
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

-- Q.13
SELECT
E.EMPNO,
D.DNAME,
D.LOC
FROM EMP E
FULL OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;


