
-- RESTRICTING AND SORTING DATA
-- Q.1.
SELECT ENAME, SAL, COMM 
FROM EMP 
WHERE COMM IS NOT NULL AND COMM > 0
ORDER BY 2 DESC, 3 DESC;

-- Q.2.
SELECT DISTINCT JOB 
FROM EMP;

-- Q.3.
SELECT EMPNO AS "Emp #", ENAME AS "Employee", JOB AS "Job", HIREDATE AS "Hire Date"
FROM EMP;

-- Q.4.
SELECT ENAME || ', ' || JOB AS "Employee and Title"
FROM EMP;

-- Q.5.
SELECT ENAME || ',' || JOB || ',' || HIREDATE || ',' || MGR AS THE_OUTPUT
FROM EMP;

-- Q.6.
SELECT ENAME, JOB, HIREDATE
FROM EMP
WHERE ENAME IN ('SCOTT', 'TURNER')
ORDER BY HIREDATE ASC;

-- Q.7.
SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO IN (20, 30)
ORDER BY ENAME ASC;

-- Q.8.
SELECT ENAME AS "Employee", SAL AS "Monthly Salary"
FROM EMP
WHERE (SAL BETWEEN 2000 AND 3000) 
  AND DEPTNO IN (20, 30);

  --Q.9.
  SELECT ENAME, HIREDATE
  FROM EMP
  WHERE HIREDATE BETWEEN '01-JAN-1981' AND '31-DEC-1981';
  
  --Q.10.
  SELECT ENAME, SAL
FROM EMP
WHERE SAL > &user_salary_amount;

--Q.11.
SELECT ENAME, JOB
FROM EMP
WHERE MGR IS NULL;

--Q12.
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE MGR = &manager_id
ORDER BY &sort_column_position_or_name;

--Q13.
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE MGR = &mgr_id
ORDER BY &select_sort_column;

--Q14.
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '__A%';

-- Q15.
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%A%' AND ENAME LIKE '%S%';

--Q16.
SELECT ENAME, JOB, SAL
FROM EMP
WHERE JOB = 'CLERK' 
  AND SAL IN (800, 950, 1300);




